# --- DARK FOREST / GLASS ---

# Cores Principais
# Fundo quase carvão/esverdeado escuro, texto em prateado envelhecido
foreground            #d3c6aa
background            #171717
selection_foreground  #1e2326
selection_background  #a7c080

# Estilo da Janela 
window_padding_width  10
active_border_color   #a7c080
inactive_border_color #272e33
hide_window_decorations yes

# Cursor (Verde Musgo)
cursor                #a7c080
cursor_text_color     #1e2326
cursor_shape          beam

# --- CORES DO TERMINAL (Paleta Everforest) ---

# Black / Grey (Sombras)
color0  #272e33
color8  #475258

# Red (Vermelho terroso/outono)
color1  #e67e80
color9  #e67e80

# Green (Verde floresta)
color2  #a7c080
color10 #a7c080

# Yellow (Ouro velho/âmbar)
color3  #dbbc7f
color11 #dbbc7f

# Blue (Azul ardósia/acinzentado)
color4  #7fbbb3
color12 #7fbbb3

# Magenta (Púrpura suave/místico)
color5  #d699b6
color13 #d699b6

# Cyan (Ciano esverdeado/água)
color6  #83c092
color14 #83c092

# White (Prata/Pergaminho)
color7  #d3c6aa
color15 #d3c6aa

# --- FONTE ---
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# --- PERFORMANCE E TRANSPARÊNCIA ---
# background_opacity 0.4 # valor da waybar = 0.27
background_opacity 0.4 