general {
    lock_cmd = pidof hyprlock || hyprlock       
    before_sleep_cmd = pidof hyprlock || hyprlock    # <-- Mudamos aqui! Chama o hyprlock direto
    after_sleep_cmd = hyprctl dispatch dpms on  
}

# 1. Reduzir o brilho da tela (5 minutos)
listener {
    timeout = 330
    on-timeout = brightnessctl -s set 10         # reduz o brilho para 10%
    on-resume = brightnessctl -r                 # restaura o brilho ao voltar
}


# 3. Bloquear a tela (10 minutos)
listener {
    timeout = 600
    on-timeout = loginctl lock-session            # chama o comando de lock configurado no general
}

# 4. Desligar o monitor (15 minutos)
listener {
    timeout = 930
    on-timeout = hyprctl dispatch dpms off        # desliga a tela
    on-resume = hyprctl dispatch dpms on          # liga a tela ao detectar atividade
}

# 5. Suspender o PC (30 minutos)
# listener {
#     timeout = 1800
#     on-timeout = systemctl suspend                
# }
