# --- FUNDO: EFEITO VIDRO FOSCO ---
background {
    monitor =
    path = /home/david/.cache/current_wallpaper.png
    blur_passes = 2
    blur_size = 4
    noise = 0.05
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
    fade_in = 0.5
}

# --- RELÓGIO PRINCIPAL ---
label {
    monitor =
    text = $TIME
    color = rgb(255, 255, 255) # Tom de pergaminho/prata
    font_size = 300
    font_family = JetBrainsMono Nerd Font
    position = 0, 150
    halign = center
    valign = center
}

# --- DATA ---
label {
    monitor =
    text = cmd[update:18000000] echo "<b> $(date +'%A, %d de %B') </b>"
    color = rgb(255, 255, 255)
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    position = 0, -100
    halign = center
    valign = center
}

# --- CLIMA DINÂMICO ---
label {
    monitor =
    # O jq pega a temperatura, arredonda, e busca a sensação térmica (feels like)
    text = cmd[update:1000] echo "$(jq -r '" " + (.current.temperature_2m | round | tostring) + "°C | " + (.current.relative_humidity_2m | tostring) + "% UR"' ~/.cache/waybar-weather.json 2>/dev/null)"
    color = rgb(255, 255, 255)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, -160
    halign = center
    valign = center
}

# --- CAIXA DE SENHA  ---
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(255, 255, 255) # Tom de pergaminho/prata
    inner_color = rgba(40, 40, 40, 0.50)    # Fundo Carvão
    font_color = rgb(255, 255, 255)  # Texto Pergaminho
    fade_on_empty = false
    placeholder_text = <i>Digite a senha...</i>
    hide_input = false
    position = 0, -300
    halign = center
    valign = center

    check_color = rgb(215, 153, 33) # Amarelo Gruvbox
    fail_color = rgb(204, 36, 29)   # Vermelho Gruvbox
    fail_text = <i>Senha incorreta!</i>
}


# --- BLOCO ---
 general {
    no_fade_in = false
    no_fade_out = false
    hide_cursor = true
    grace = 0
    disable_loading = true
    ignore_empty_input = true
}


# --- CURRENT SONG ---
label {
    monitor =
    # Chama o script e usa o echo para garantir que o Hyprlock receba uma string limpa
    text = cmd[update:1000] echo "$($HOME/.config/hypr/scripts/hyprinfo.sh)"
    color = rgb(255, 255, 255)
    shadow_passes = 5
    shadow_size = 1
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, 50
    halign = center
    valign = bottom
}
