# Desativa a tentativa do MPV de mudar o espaço de cores do monitor (Culpado #1)
target-colorspace-hint=no

# Força o driver de vídeo padrão, que é mais estável no Wayland que o 'gpu-next'
vo=gpu

# Opcional: Se o acima não resolver, descomente a linha abaixo.
# Isso força o MPV a usar o protocolo Wayland puro, evitando camadas extras.
# gpu-context=wayland
